name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build-type: [Debug, Release]
    name: Build ${{ matrix.build-type }}
    runs-on: windows-2025

    steps:
      - name: Set variables for artifact names
        id: vars
        shell: bash
        run: |
          echo "type=${{ matrix.build-type }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d_%H%M%S')" >> $GITHUB_OUTPUT
          GIT_REF=${{ github.head_ref || github.ref_name }}
          # Replace illegal file system characters in branch name
          echo "git_ref=${GIT_REF//[\":<>|*?\/\\]/_}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Remove VERBOSE
        shell: bash
        if: matrix.build-type == 'Release'
        run: |
          sed -i "s/#define VERBOSE//" dllmain/dllmain.h

      - name: Build ${{ matrix.build-type }}
        run: |
          msbuild re4_tweaks.sln /p:Configuration=${{ matrix.build-type }} /p:PostBuildEventUseInBuild=false

      - name: Create default configuration file
        shell: bash
        working-directory: ./${{ matrix.build-type }}
        run: |
          mkdir re4_tweaks
          cp ../settings/settings.ini ./dinput8.ini
          cp ../settings/trainer_settings.ini ./re4_tweaks/trainer.ini

      - name: Copy game data files
        shell: bash
        working-directory: ./${{ matrix.build-type }}
        run: |
          cp -r ../external/EnglishSubtitleData/Bin32/re4_tweaks/ ./
          cp -r ../dist/Bin32/re4_tweaks/ ./

      - name: Upload ${{ matrix.build-type }}
        uses: actions/upload-artifact@v4
        with:
          path: |
            ${{ matrix.build-type }}/re4_tweaks/
            ${{ matrix.build-type }}/dinput8.dll
            ${{ matrix.build-type }}/dinput8.ini
            ${{ matrix.build-type }}/dinput8.pdb
          name: re4_tweaks_${{ steps.vars.outputs.type }}_${{ steps.vars.outputs.git_ref }}_${{ steps.vars.outputs.date }}

permissions:
  contents: read
